"""Pytest configuration: minimal env and thread caps for local smoke tests."""

from __future__ import annotations

import os
from pathlib import Path

# Dummy values only — tests must not read real data, train models, or use GPUs.
_MINIMAL_ENV: dict[str, str] = {
    "PROJECT_ROOT": "/tmp/dldl_pytest",
    "DATA_DIR": "/tmp/dldl_pytest/data/raw",
    "LABELS_PATH": "/tmp/dldl_pytest/data/labels.txt",
    "DATA_PATH": "/tmp/dldl_pytest/data/processed_dataset.pt",
    "TRAIN_LABELS_PATH": "/tmp/dldl_pytest/data/processed_labels.pt",
    "PROG_DIR": "/tmp/dldl_pytest/train_progress",
    "JOB_ID": "pytest_run",
    "CPU_USE": "0.2",
    "PREPROCESSOR_MAX_WORKERS": "1",
    "EARLY_STOPPING_PATIENCE": "10",
    "LEARNING_RATE": "0.001",
    "NUM_EPOCHS": "2",
    "LOG_INTERVAL": "1",
    "WEIGHT_DECAY": "0.0001",
    "DROPOUT_RATE": "0.1",
    "BATCH_SIZE": "4",
    "LR_SCHEDULER": "false",
    "LR_SCHEDULER_FACTOR": "0.5",
    "LR_SCHEDULER_PATIENCE": "5",
    "GRADIENT_CLIP": "1.0",
    "DATALOADER_NUM_WORKERS": "0",
    "CLS_POS_WEIGHT": "1.0",
    "DECISION_THRESHOLD": "0.5",
    "MIN_PRECISION": "0.90",
    "FBETA": "1.8",
    "CONV1_FILTERS": "8",
    "CONV1_KERNEL": "3",
    "CONV1_PADDING": "1",
    "CONV2_FILTERS": "8",
    "CONV2_KERNEL": "3",
    "CONV2_PADDING": "1",
    "CONV3_FILTERS": "8",
    "CONV3_KERNEL": "3",
    "CONV3_PADDING": "1",
    "CONV4_FILTERS": "8",
    "CONV4_KERNEL": "3",
    "CONV4_PADDING": "1",
    "POOL_SIZE": "2",
    "FC1_SIZE": "16",
    "FC2_SIZE": "8",
    "HP_TUNE_LR_MIN": "1e-5",
    "HP_TUNE_LR_MAX": "1e-2",
    "HP_TUNE_DROPOUT_MIN": "0.0",
    "HP_TUNE_DROPOUT_MAX": "0.5",
    "HP_TUNE_ALLOWED_EPOCHS": "2,4",
    "HP_TUNE_NUM_INITIAL_TRIALS": "2",
    "HP_TUNE_WEIGHT_DECAY_LOG_MIN": "-6.0",
    "HP_TUNE_WEIGHT_DECAY_LOG_MAX": "-2.0",
    "HP_TUNE_ALLOWED_BATCH_SIZES": "4,8",
    "HP_TUNE_GRADIENT_CLIP_MIN": "0.0",
    "HP_TUNE_GRADIENT_CLIP_MAX": "1.0",
    "HP_TUNE_LR_SCHEDULER_FACTOR_MIN": "0.1",
    "HP_TUNE_LR_SCHEDULER_FACTOR_MAX": "0.9",
    "HP_TUNE_LR_SCHEDULER_PATIENCE_MIN": "1",
    "HP_TUNE_LR_SCHEDULER_PATIENCE_MAX": "5",
    "HP_TUNE_EARLY_STOPPING_PATIENCE_MIN": "1",
    "HP_TUNE_EARLY_STOPPING_PATIENCE_MAX": "5",
    "HP_TUNE_CLS_POS_WEIGHT_MIN": "1.0",
    "HP_TUNE_CLS_POS_WEIGHT_MAX": "2.0",
    "HP_TUNE_RANDOM_INSERT_EVERY": "0",
    "HP_TUNE_EI_XI": "0.05",
    "HP_TUNE_DIR": "/tmp/dldl_pytest_hp_tune",
    "HP_TUNE_MAX_TRIALS": "2",
    "HP_TUNE_QUEUE": "debug",
    "HP_TUNE_TRAIN_WALLTIME": "0:10:00",
    "HP_TUNE_MAX_RETRIES": "0",
    "TRIAL_TIMEOUT": "60",
    "ARCH_TUNE_DIR": "/tmp/dldl_pytest_arch_tune",
    "ARCH_TUNE_CONV_FILTERS": "8,16",
    "ARCH_TUNE_KERNELS": "3,5",
    "ARCH_TUNE_POOL_SIZES": "2",
    "ARCH_TUNE_FC1_MIN": "8",
    "ARCH_TUNE_FC1_MAX": "16",
    "ARCH_TUNE_FC2_MIN": "4",
    "ARCH_TUNE_FC2_MAX": "8",
    "ARCH_TUNE_NUM_INITIAL_TRIALS": "2",
    "ARCH_TUNE_RANDOM_INSERT_EVERY": "0",
    "ARCH_TUNE_EI_XI": "0.05",
    "DLDL_CONDASH": "/tmp/dldl_pytest/conda.sh",
    "CONDA_ENV": "dldl",
    "TMPDIR": "/tmp",
    "OPENBLAS_NUM_THREADS": "1",
    "OMP_NUM_THREADS": "1",
    "MKL_NUM_THREADS": "1",
    "NUMEXPR_NUM_THREADS": "1",
    "TORCH_NUM_THREADS": "1",
}

for _key, _value in _MINIMAL_ENV.items():
    os.environ.setdefault(_key, _value)

Path(os.environ["HP_TUNE_DIR"]).mkdir(parents=True, exist_ok=True)
